version: '3.8'

services:
  fastapi-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "443:443"
      - "4433:4433"
    cap_add:
      - NET_ADMIN  # Даем права на управление сетью
    environment:
      - NETWORK_LATENCY=100ms
      - NETWORK_LOSS=1%
      - NETWORK_BANDWIDTH=10mbit
    networks:
      - test-network

networks:
  test-network:
    driver: bridge